server:
  port: 8080

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  config:
    import: optional:configserver:http://localhost:8888  # Optional Config Server URL

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery for routing
      routes:
        - id: PRODUCT
          uri: lb://PRODUCT
          predicates:
              - Path=/api/products/**
        - id: Inventory_service
          uri: lb://INVENTORY
          predicates:
              - Path=/api/inventory/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
